# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dict_add.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='dict_add.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0e\x64ict_add.proto\x1a\x1cgoogle/protobuf/struct.proto\"*\n\x04\x44ict\x12\"\n\x01s\x18\x01 \x01(\x0b\x32\x17.google.protobuf.Struct2#\n\x07\x44ictAdd\x12\x18\n\x08\x41\x64\x64_Dict\x12\x05.Dict\x1a\x05.Dictb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_struct__pb2.DESCRIPTOR,])




_DICT = _descriptor.Descriptor(
  name='Dict',
  full_name='Dict',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='s', full_name='Dict.s', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=90,
)

_DICT.fields_by_name['s'].message_type = google_dot_protobuf_dot_struct__pb2._STRUCT
DESCRIPTOR.message_types_by_name['Dict'] = _DICT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Dict = _reflection.GeneratedProtocolMessageType('Dict', (_message.Message,), dict(
  DESCRIPTOR = _DICT,
  __module__ = 'dict_add_pb2'
  # @@protoc_insertion_point(class_scope:Dict)
  ))
_sym_db.RegisterMessage(Dict)



_DICTADD = _descriptor.ServiceDescriptor(
  name='DictAdd',
  full_name='DictAdd',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=92,
  serialized_end=127,
  methods=[
  _descriptor.MethodDescriptor(
    name='Add_Dict',
    full_name='DictAdd.Add_Dict',
    index=0,
    containing_service=None,
    input_type=_DICT,
    output_type=_DICT,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DICTADD)

DESCRIPTOR.services_by_name['DictAdd'] = _DICTADD

# @@protoc_insertion_point(module_scope)
